# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Development Builds

on: [push]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      with:
        script: |
          let release = (await github.rest.repos.listReleases({
            owner: 'gnembon',
            repo: 'fabric-carpet',
            per_page: 2
          })).data[1];
          console.log(github.repository);
          //if (release.name.includes('1.4.92')) core.setFailed('Version number is the same as previous release!')
